apiVersion: apps/v1
kind: Deployment
metadata:
  name: claimer-devices-mongo-depl
spec:
  selector:
    matchLabels:
      app: claimer-devices-mongo
  template:
    metadata:
      labels:
        app: claimer-devices-mongo
    spec:
      containers:
      - name: claimer-devices-mongo
        image: mongo
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: claimer-devices-mongo-srv
spec:
  selector:
    app: claimer-devices-mongo
  ports:
  - name: claimer-devices-mongo-db
    protocol: TCP
    port: 27017
    targetPort: 27017

